bank: dict[str, tuple[str, ...]] = {
    "absence": ("absense", "absentse", "abcense", "absance"),
    "acceptable": ("acceptible",),
    "accidentally": ("accidently", "accidentaly"),
    "accommodate": ("accomodate", "acommodate"),
    "achieve": ("acheive",),
    "acknowledge": ("acknowlege",),
    "acquaintance": ("acquaintence", "aquaintance"),
    "acquire": ("aquire", "adquire"),
    "acquit": ("aquit",),
    "acreage": ("acrage", "acerage"),
    "address": ("adress",),
    "adultery": ("adultary",),
    "advisable": ("adviseable", "advizable"),
    "aggression": ("agression",),
    "aggressive": ("agressive",),
    "allegiance": ("allegaince", "allegience", "alegiance"),
    "almost": ("allmost",),
    "amateur": ("amatuer", "amature"),
    "annually": ("anually", "annualy"),
    "apparent": ("apparant", "aparent", "apparrent", "aparrent"),
    "arctic": ("artic",),
    "argument": ("arguement",),
    "atheist": ("athiest", "athist"),
    "awful": ("awfull", "aweful"),
    "because": ("becuase", "becasue"),
    "beautiful": ("beatiful",),
    "becoming": ("becomeing",),
    "beginning": ("begining",),
    "believe": ("beleive",),
    "bellwether": ("bellweather",),
    "benefit": ("benifit",),
    "business": ("buisness",),
    "calendar": ("calender",),
    "camouflage": ("camoflage", "camoflague"),
    "Caribbean": ("Carribean",),
    "category": ("catagory",),
    "cemetery": ("cemetary",),
    "changeable": ("changable",),
    "chief": ("cheif",),
    "colleague": ("collaegue", "collegue"),
    "column": ("colum",),
    "coming": ("comming",),
    "committed": ("commited", "comitted"),
    "comparison": ("comparsion",),
    "concede": ("conceed",),
    "congratulate": ("congradulate",),
    "conscientious": ("consciencious",),
    "conscious": ("concious", "consious"),
    "consensus": ("concensus",),
    "controversy": ("contraversy",),
    "coolly": ("cooly",),
    "daiquiri": ("dacquiri", "daquiri"),
    "deceive": ("decieve",),
    "definite": ("definate", "definit"),
    "definitely": ("definitly", "definately", "definatly", "defiantly"),
    "desperate": ("desparate",),
    "difference": ("diffrence",),
    "dilemma": ("dilema",),
    "disappoint": ("dissapoint",),
    "disastrous": ("disasterous",),
    "drunkenness": ("drunkeness",),
    "dumbbell": ("dumbell",),
    "embarrass": ("embarass",),
    "equipment": ("equiptment",),
    "exceed": ("excede",),
    "exhilarate": ("exilerate",),
    "existence": ("existance",),
    "experience": ("experiance",),
    "extreme": ("extreem",),
    "fascinating": ("facinating",),
    "fiery": ("firey",),
    "fluorescent": ("flourescent",),
    "foreign": ("foriegn",),
    "friend": ("freind",),
    "fulfil": ("fulfill",),
    "gauge": ("guage",),
    "grateful": ("gratefull", "greatful"),
    "great": ("grate", "grat"),
    "guarantee": ("garantee", "garentee", "garanty"),
    "guidance": ("guidence",),
    "harass": ("harrass",),
    "height": ("heighth", "heigth"),
    "hierarchy": ("heirarchy",),
    "humorous": ("umerous",),
    "hygiene": ("hygene", "hygine", "hiygeine", "higeine", "hygeine"),
    "ignorance": ("ignorence",),
    "imitate": ("immitate",),
    "immediately": ("imediately",),
    "indict": ("indite",),
    "independent": ("independant",),
    "indispensable": ("indispensible",),
    "inoculate": ("innoculate",),
    "intelligence": ("inteligence", "intelligance"),
    "judgment": ("judgement",),
    "leisure": ("liesure",),
    "liaison": ("liason",),
    "library": ("libary", "liberry"),
    "lightning": ("lightening",),
    "lose": ("loose",),
    "maintenance": ("maintainance", "maintnance"),
    "marshmallow": ("marshmellow",),
    "medieval": ("medeval", "medevil", "mideval"),
    "memento": ("momento",),
    "millennium": ("millenium", "milennium"),
    "miniature": ("miniture",),
    "minuscule": ("miniscule",),
    "misspell": ("mispell", "misspel"),
    "necessary": ("neccessary", "necessery"),
    "niece": ("neice",),
    "neighbour": ("nieghbor",),
    "noticeable": ("noticable",),
    "occasion": ("occassion",),
    "occasionally": ("occasionaly", "occassionally"),
    "occurrence": ("occurrance", "occurence"),
    "occurred": ("occured",),
    "omission": ("ommision", "omision"),
    "original": ("orignal",),
    "outrageous": ("outragous",),
    "parliament": ("parliment",),
    "pastime": ("passtime", "pasttime"),
    "perceive": ("percieve",),
    "perseverance": ("perseverence",),
    "personnel": ("personell", "personel"),
    "plagiarize": ("plagerize",),
    "playwright": ("playright", "playwrite"),
    "possession": ("posession", "possesion"),
    "potatoes": ("potatos",),
    "precede": ("preceed",),
    "presence": ("presance",),
    "principle": ("principal",),
    "privilege": ("privelege", "priviledge"),
    "professor": ("professer",),
    "protester": ("protestor",),
    "promise": ("promiss",),
    "pronunciation": ("pronounciation",),
    "proof": ("prufe",),
    "publicly": ("publically",),
    "quarantine": ("quarentine",),
    "queue": ("que",),
    "questionnaire": ("questionaire", "questionnair"),
    "readable": ("readible",),
    "really": ("realy",),
    "receive": ("recieve",),
    "receipt": ("reciept",),
    "recommend": ("recomend", "reccommend"),
    "referred": ("refered",),
    "reference": ("referance", "refrence"),
    "relevant": ("relevent", "revelant"),
    "religious": ("religous", "religius"),
    "repetition": ("repitition",),
    "restaurant": ("restarant", "restaraunt"),
    "rhyme": ("rime",),
    "rhythm": ("rythm", "rythem"),
    "secretary": ("secratary", "secretery"),
    "seize": ("sieze",),
    "separate": ("seperate",),
    "sergeant": ("sargent",),
    "similar": ("similer",),
    "speech": ("speach",),
    "successful": ("succesful", "successfull", "sucessful"),
    "supersede": ("supercede",),
    "surprise": ("suprise", "surprize"),
    "tomatoes": ("tomatos",),
    "tomorrow": ("tommorow", "tommorrow"),
    "twelfth": ("twelth",),
    "tyranny": ("tyrany",),
    "underrate": ("underate",),
    "until": ("untill",),
    "vacuum": ("vaccuum", "vaccum", "vacume"),
    "vehicle": ("vehical",),
    "vicious": ("visious",),
    "weather": ("wether", "whether"),
    "weird": ("wierd",),
    "welfare": ("wellfare", "welfair"),
    "whether": ("wether",),
    "wilful": ("willful",),
    "withhold": ("withold",),
    "writing": ("writting", "writeing"),
}

banked: dict[tuple[str, ...], str] = {v: k for k, v in bank.items()}

flattened_dict: dict[str, str] = {}

for misspellings, correct_spelling in banked.items():
    for misspelling in misspellings:
        flattened_dict[misspelling] = correct_spelling
    continue
